### ISSUE TITLE
Switch remove card to the collections component map

### ISSUE THREAD

**Issue by grassfinn** [grassfinn/MtgCollection#4]
The button is a part of the card component, so when you hover over it, it doesn't look like the card is hovering due to the button being transformed.  The card should be the only piece that transforms not the button as well.

**Comment by J3ffJessie** [comment]
Struggling with what exactly you mean by this issue.  I got the app up and running and on the collection screen when I hover the card it gets it transformation to pop up a little bit and the button doesn't do anything at all.  When hovering over the button and not the card, the background on the remove button gets a little darker and the card does not animate.  Is that the expected behavior that you are looking for or something different?

**Comment by grassfinn** [comment]
I think the previous PR fixed the issue. If you are still wanting to contribute I can add an issue of another simple feature or tweak to add.
